# UTF-8 require.

CreateAccountOnJoin: true

DefaultBalance: 10000.0

TopCommandEntryPerPage: 10

Format:
  MergeSpace: true
  Trim: true
  Major:
    Single: "dollar"
    Plural: "dollars"
  Minor:
    Single: "cent"
    Plural: "cents"
  Format: "[%Major%] [%MajorCurrency%] [%Minor%] [%MinorCurrency%]"
# Format macro(Example: 123.45)
# [%Major%]->123
# [%Minor%]->45
# [%All%]->123.45
# [%MajorCurrency%]->Major currency.
# [%MinorCurrency%]->Minor currency.
# Format example:
#   "[%Major%] [%MajorCurrency%] [%Minor%] [%MinorCurrency%]":
#     123.45->123 dollars 45 cents
#     1.35->1 dollar 35 cents
#   "[%Major%] YEN":
#     123.45->123 YEN
#     1.35->1 YEN
#   "$[%All%]":
#     123.45->$123.45
#     1.35->$1.35

# Info: What is MergeSpace?
# Summarizes the consecutive space.
# [%Minor%] and [%MinorCurrency%] will be replaced in the blank in the case of a 0.
# Example(amount:1.0,Format:"[%Major%] [%MajorCurrency%] [%Minor%] [%MinorCurrency%]")
#   MergeSpace: false -> [1 doller  ]
#   MergeSpace: true  -> [1 doller ]
#
# Info: What is Trim?
# Remove the first and last space.
# [1 doller ]
#   Trim: false -> [1 doller ]
#   Trim: true  -> [1 doller]

Database:
  # If it is less than 1, the default value is used.(default:10)
  Poolsize: -1
  # Timeout in milliseconds.(default:600000(10 minutes))
  Timeout: -1
  # Database type. (sqlite/mysql)
  Type: sqlite
  SQLite:
    File: "jecon.db"
  MySQL:
    Host: "localhost:3306"
    Name: "jecon"
    User: "root"
    Pass: "your_mysql_password"
    Prefix: "jecon_"
    Propaties:
      "useSSL": "false"
      "useServerPrepStmts": "true"